### ISSUE TITLE
AGS: mixed liquor concentration

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#14]
7.	Have the mixed liquor concentration show up at 8,000 mg/l as a default.

**Comment by chukon** [comment]
Where is this change to be made?

**Comment by sbainbridge** [comment]
![nereda edit](https://cloud.githubusercontent.com/assets/27778784/26111743/8f4be7d6-3a1b-11e7-84f8-8ef7663a0860.png)


Hi Chuck, 

Please reflect the mixed liquor concentration default to say 8,000 mg/l instead of 4,500 mg/l. 

In addition, please reflect the title of the "SBR Match Stuff: screen to reflect "AGS Match Stuff" 

This screen appears after the "Match Basin" button is clicked in the Design Calculations tab. 

Please let me know if you have any questions. 

Thank you, 

Sophia

**Comment by chukon** [comment]
Ready to test

**Comment by bquimby** [comment]
this is done
