### ISSUE TITLE
AGS: Equipment Tab Labels

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#17]
Influent Manifold >  Influent Distribution System
Decanter Calcs > Sludge Buffer

**Comment by chukon** [comment]
This has been fixed. Please restart APD Dev, test and close.

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
Hi Chuck, 

The influent distribution systems seems to be correct. 

However the sludge removal system in the AGS basins still reads "decanter calcs" Please see the screenshot below. 

![image](https://cloud.githubusercontent.com/assets/27778784/25956724/16629a50-3632-11e7-85a8-eb0acb645ccf.png)

Instead of decanter calcs it should read "sludge removal system" 

Thank you.

**Comment by chukon** [comment]
decanter calcs now reads "sludge removal system"

**Comment by bquimby** [comment]
This is fixed.
