### ISSUE TITLE
Report: Water Level Correction Tank in Report

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#26]
Water Level Correction Tank in Report

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
Hi Chuck, 
On the build for water level correction tank on the items to select says "effluent weir assembly" instead of AquaDDM mixers with mooring. 
![image](https://cloud.githubusercontent.com/assets/27778784/25392758/235b21fe-299f-11e7-8450-f694be3926e7.png)

On the summary the description is great however it seems that periods are a few spaces away from the end of the sentence. In addition we do not need the volume calculation on the summary. Plus the font for the Max Flow Rate and average power required is different. Please match the font of the No./ Basin and Basin Vol. Can you also add the letter "y" to the word geometry? 

![image](https://cloud.githubusercontent.com/assets/27778784/25393021/f78272e8-299f-11e7-84e5-a0d7b4274bbc.png)



Please let me know if you have any questions. Thank you!

**Comment by ckonkolaqua** [comment]
Sophia,

These are already in active bug list

https://github.com/aquaaerobic/AquaNereda/issues/5

**Comment by sbainbridge** [comment]
Hi Chuck, 

Just to reiterate what we talked about in yesterday's meeting. 

Please omit "mixer and Effluent Weir assembly" from the equipment list. Again I'm sorry to telling you to add it in! I was confusing this with the pre-eq where we do need a mixer.  


The comments above regarding the summary page still apply. In addition, please add in the conversion calculations to calculate gpm to m3/hr. 

Please let me know if you have any questions. 

Thank you - Sophia

**Comment by chukon** [comment]
The efluent weir assembly has been removed from equipment tab and the report font sizes have been fixed for WLCT.

Please restart APD Dev, test and close. - Chuck

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
[NeredaPrelimPkg1MAIN.pdf](https://github.com/aquaaerobic/AquaNereda/files/1004931/NeredaPrelimPkg1MAIN.pdf)

Hi Chuck, 

Please see some of the units that need to be changed on the water level correction tank summary. 

Thank you, 

Sophia

**Comment by chukon** [comment]
@sbainbridge This is ready to test

**Comment by sbainbridge** [comment]
Thank you! This looks good.
