### ISSUE TITLE
Report: Sludge Buffer

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#27]
Report: Sludge Buffer

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
Hi Chuck, 

A few items to mention here.  Below is a screenshot of what the sludge buffer summary currently looks like. 
![image](https://cloud.githubusercontent.com/assets/27778784/25392499/667cab20-299e-11e7-9031-494a6161f7a6.png)


Can you please reflect the max basin volume to reflect the unit in gallons instead of cubic feet? 

The max pump flow per basin reflects "1 per basin" I understand that for now this is a value for the AE's to chance. Can we please have units reflected here in gpm and also m3/hr?

**Comment by sbainbridge** [comment]
Hi Chuck, 

In addition, 

I am not able to change a part to add pumps in the sludge buffer. Would it be possible to add a pump tab to the sludge buffer that we would have it in the SBR/ Post-eq/ or Pre-eq? 

![image](https://cloud.githubusercontent.com/assets/27778784/25393279/b1d7f974-29a0-11e7-8272-ba25f905f86f.png)

**Comment by ckonkolaqua** [comment]
Yup, on the list. You will have stub for Pump and Sludge Manifold.

See https://github.com/aquaaerobic/AquaNereda/issues/20

**Comment by chukon** [comment]
Ready to Test Sludge Buffer Report Changes and Close Issue if ok.

**Comment by sbainbridge** [comment]
This looks good to me!
